databases:
  - name: my_account
    databaseName: my_account_app
    user: my_account_app_user

services:
  - type: web
    name: My-account-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_account_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
